server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  freemarker:
    check-template-location: true
    # \u8BBE\u7F6E\u6A21\u677F\u540E\u7F00\u540D
    suffix: .ftl
    # \u8BBE\u7F6E\u6587\u6863\u7C7B\u578B
    content-type: text/html
    # \u8BBE\u7F6E\u9875\u9762\u7F16\u7801\u683C\u5F0F
    charset: UTF-8
    # \u8BBE\u7F6E\u9875\u9762\u7F13\u5B58
    cache: false
    # \u8BBE\u7F6Eftl\u6587\u4EF6\u8DEF\u5F84
    template-loader-path:  classpath:/templates
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    #classic_compatible
    settings:
      classic_compatible: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.model
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
